### ISSUE TITLE
Subscription Feature.

### ISSUE THREAD

**Issue by rizrmd** [romanzy313/trpc-uwebsockets#2]
Hi, Great job

I need native subscription feature for already awesome trpc-uwebsocket. I'm willing to create a pull request for this.
Do you have suggestion where to start ?

**Comment by romanzy-1612** [comment]
Hello,

I've used official express connector as a template to implement this. The
implementation is very similar.

The reason I haven't implemented subscriptions is that a big update (v10)
is going to change a lot of internals. Also, subscription api is not stable
and it is constantly tweaked in the trpc next branch.

**Comment by dzcpy** [comment]
Hi, are you still going to work on it? v10 seems to be a bit more stable now. Is subscription feature going to be added?

**Comment by yovanoc** [comment]
Yeah I really would like to see this too

**Comment by romanzy313** [comment]
I am currently not using uWebSockets for my project, had to change for something more feature rich. After my project is delivered, I'd love to finish up this library, and subscriptions are definately a good fit for uWebSockets as it is too "raw" to be used as is.

Implementation is difficult because of types... Typescript gets very confusing, messy, and difficult when complex generics are involved. That is definately a case with trpc, as all definitions need to be carried from procedures up to the topmost router. I'd say trpc is typescript wizardry 😅

For the current implementation I reused most parts of express connector, including the "handle" function, which basically does everything. Trpc V10 subscription is heavily tied to ws library and it makes it hard to change underlying logics... A lot of types need to be rewritten from scratch, while keeping feature parity 🙃

**Comment by yovanoc** [comment]
I've done it, and it's not that hard but trpc don't export types that we need. I will open a PR to the official repo to see if they want this adapter, and we will see.

**Comment by dzcpy** [comment]
> I've done it, and it's not that hard but trpc don't export types that we need. I will open a PR to the official repo to see if they want this adapter, and we will see.

Great, thanks for your effort!

**Comment by yovanoc** [comment]
If they don't want it, I will ask then to export some types and add it to this repo instead !

**Comment by b0o** [comment]
@yovanoc Did you ever open that PR? If not, is your implementation available somewhere?

**Comment by yovanoc** [comment]
@b0o  Yeah its working on my side after asking trpc to export some types. They don't want the adapter though so it will be better here I think if  @romanzy313 wants it.

**Comment by b0o** [comment]
@yovanoc I ended up writing my own 😅

**Comment by romanzy313** [comment]
I have implemented subscriptions. Install beta version to try it out! My implementation passes the same tests as fastify web-socket adapter, but I haven't tried it on a real application. There could be errors around edge cases.

**Comment by yovanoc** [comment]
oh sorry didn't remember this issue! I've done a lot of things to have it production ready on my side, as compute the context on the upgrade callback and not open then close I could try to PR you if you want

**Comment by yovanoc** [comment]
@romanzy313 https://github.com/romanzy313/trpc-uwebsockets/pull/4
hope you will like it
